apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: microservices
spec:
  ports:
  - port: 5000
  selector:
    tier: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: recipe-app
        image: corcoran909/rapp:alt
        ports:
          - containerPort: 5000
