version: "3.8"
services:
  webapp:
    image: rapp
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 1
  db:
    image: dbase
    deploy: 
      replicas: 1
    ports:
      - target: 3306
      - published: 3006
    volumes:
    - /c/Users/Mike/Desktop/code/Recipe_planner/db

      