version: "3.8"
services:
  webapp:
    image: corcoran909/recipe-app:<tag>
    name: recipe-app
    ports:
    - target: 5050
      published: 5050
    deploy:
      replicas: 1
    volumes:
      - type: bind
      - source: /Users/michaelcorcoran/Documents/docker-mounts
      - target: /db
