apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: microservices
  namespace: recipe-app
spec:
  ports:
  - port: 5050
  selector:
    tier: front-end
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: recipe-app
    tier: front-end
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: recipe-app
        image: corcoran909/rapp
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5050
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
