apiVersion: v1
kind: Service
metadata:
  name: recipe-app-db
  labels:
    app: recipe-app
  namespace: recipe-app
spec:
  type: ExternalName
  ExternalName: recipe-app-db.c9c6yyvyhcc2.eu-west-1.rds.amazonaws.com
  ports:
    - port: 3306
