apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: microservices
spec:
  ports:
  - port: 3306
  selector:
    tier: data 
---
apiVersion: apps/v1 # apps API group
kind: Deployment
metadata:
  name: data-tier
  labels:
    app: microservices
    tier: data
spec: 
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      labels:
        app: microservices
        tier: data
    spec: # Pod spec
      volumes:
        - name: data-tier-storage
          persistentVolumeClaim:
            claimName: data-tier-volume-claim
      containers:
        - name: appdb
          image: corcoran909/dbase:alt
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: data-tier-storage
      

